CorpServer/Controllers/SystemController.cs
using BL;
using Models;
using Models.Common;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Tools;

namespace CorpServer.Controllers
{
    public class SystemController : BaseController
    {
        SystemBl systemBl = new SystemBl();
        public ActionResult Index() { return View(); }
        [HttpGet]
        public ActionResult Settings(string Message)
        {
            try
            {
                if (!string.IsNullOrEmpty(Message))
                {
                    TempData["ErrorMessage"] = Message;
                }
                ServerSetting setting = systemBl.GetServerSetting();
                return View(setting);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }
            return View();
        }
        [HttpPost]
        public ActionResult Settings(ServerSetting serverSetting)
        {
            try
            {
                bool curent_rule_status = FirewallManagement.CheckRule("RDP TCP").Enabled;
                if (curent_rule_status != serverSetting.RdpRuleStatus)
                {
                    FirewallManagement.ChangeRuleStatus("RDP TCP", serverSetting.RdpRuleStatus);
                    FirewallManagement.ChangeRuleStatus("RDP UDP", serverSetting.RdpRuleStatus);
                }
                serverSetting.RdpRuleStatus = FirewallManagement.CheckRule("RDP TCP").Enabled;
                systemBl.UpdateServerSettings(serverSetting);
                TempData["SuccessMessage"] = "Server Settings Updated Successfully!";
                return View(serverSetting);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message + ex.StackTrace;
            }
            return View();
        }


        [HttpGet]
        public JsonResult GetServerPerformance()
        {
            try
            {
                return Json(systemBl.GetServerPerformance(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return Json(new SystemPerformance());
            }
        }

        [HttpGet]
        public ActionResult ConnectionsPerDay()
        {
            try
            {
                var timer = DateTime.Now;
                var results = systemBl.CountConnectionsPerDay(120, 2);
                TempData["LoadingTime"] = (DateTime.Now - timer).ToFriendlyString(shortMode: 1);
                return View(results);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message + ex.StackTrace;
                return View();
            }
        }


        public void Delete(string fileName)
        {
            var path = Server.MapPath("~/Uploads/" + fileName);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            Response.Redirect("~/System/Upload");
        }

        private List<FileInfo> GetFiles()
        {
            var culture = CultureInfo.CreateSpecificCulture("en-US");
            Thread.CurrentThread.CurrentCulture = culture;
            Thread.CurrentThread.CurrentUICulture = culture;
            var directory = new DirectoryInfo(Server.MapPath("~/Uploads"));
            var files = directory.GetFiles();
            return files.ToList();
        }
        [HttpGet]
        public ActionResult Upload()
        {
            return View(GetFiles());
        }

        public ActionResult FilesPartial()
        {
            var files = GetFiles();
            return PartialView("ListFilesPartial", files);
        }
        private string CheckFileName(string defultName)
        {
            var fileName = Path.GetFileName(defultName);
            var extension = Path.GetExtension(fileName);
            var fileNameOnly = Path.GetFileNameWithoutExtension(fileName);

            // Replace invalid characters in file name with underscore
            var safeFileName = string.Concat(fileNameOnly.Split(Path.GetInvalidFileNameChars())).Trim();

            var i = 0;
            var path = Path.Combine(Server.MapPath("~/Uploads"), string.Format("{0}{1}", safeFileName, extension));
            while (System.IO.File.Exists(path))
            {
                i++;
                fileName = string.Format("{0} ({1}){2}", safeFileName, i, extension);
                path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
            }
            return path;

        }
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            try
            {
                if (file != null && file.ContentLength > 0)
                {
                    file.SaveAs(CheckFileName(file.FileName));
                    return View(GetFiles());
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                throw new HttpException(ex.Message);
            }
        }
        private static long GetFileSize(string url)
        {
            long fileSize = 0;
            WebRequest request = WebRequest.Create(url);
            request.Method = "HEAD";
            using (WebResponse response = request.GetResponse())
            {
                if (long.TryParse(response.Headers.Get("Content-Length"), out long contentLength))
                {
                    fileSize = contentLength;
                }
            }
            return fileSize;
        }
        public ActionResult UploadFromLink(string url)
        {
            try
            {
                var fileName = Path.GetFileName(url);
                fileName = CheckFileName(fileName);
                var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);

                
                long filesize = GetFileSize(url);

                // Write the download information to a text file
                string downloadInfo = string.Format("{0} &&& {1} &&& {2} &&& {3}", 
                    fileName, filesize, DateTime.Now.ToString("yyyy-MM-dd_HH:mm:ss"), url);

                using (StreamWriter writer = new StreamWriter(Server.MapPath("~/UrlUploadInfo.txt"), true))
                {
                    writer.WriteLine(downloadInfo);
                }


                WebClient client = new WebClient();
                client.DownloadFile(url, path);
                // Return a success message as a JSON response
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Upload");
            }
        }
        [HttpGet]
        [AllowAnonymous]
        public ActionResult FileViewer(string fileName)
        {
            if (!string.IsNullOrEmpty(fileName))
            {
                var culture = CultureInfo.CreateSpecificCulture("en-US");
                Thread.CurrentThread.CurrentCulture = culture;
                Thread.CurrentThread.CurrentUICulture = culture;
                var decrypred_fileName = Encryption.DeobfuscateFileName(fileName);
                string filePath = Server.MapPath("~/Uploads/" + decrypred_fileName);
                var file = new FileInfo(filePath);
                return View("FileViewer", model: file);
            }
            else
            {
                return HttpNotFound();
            }
        }
        [HttpPost]
        public JsonResult RemoveFileFromList(string fileName)
        {
            string filePath = Server.MapPath("~/UrlUploadInfo.txt");
            string tempFilePath = Path.GetTempFileName();

            StreamReader reader = null;
            StreamWriter writer = null;

            try
            {
                reader = new StreamReader(filePath);
                writer = new StreamWriter(tempFilePath);

                string line;
                while ((line = reader.ReadLine()) != null)
                {
                    if (!line.Split(new string[] { "&&&" }, StringSplitOptions.RemoveEmptyEntries)[0].EndsWith("\\" + fileName))
                    {
                        writer.WriteLine(line);
                    }
                }
            }
            finally
            {
                if (reader != null) reader.Close();
                if (writer != null) writer.Close();
            }

            System.IO.File.Delete(filePath);
            System.IO.File.Move(tempFilePath, filePath);

            return Json(new { success = true });
        }
        public ActionResult GetUploadedFilesJson()
        {
            string url_upload_path = Server.MapPath("~/UrlUploadInfo.txt");
            if (System.IO.File.Exists(url_upload_path))
            {
                var fileSizes = new Dictionary<string, Tuple<long, long, string, string>>();
                foreach (var line in System.IO.File.ReadLines(url_upload_path))
                {
                    var parts = line.Split(new string[] { "&&&" }, StringSplitOptions.RemoveEmptyEntries);
                    var filePath = parts[0];
                    var fileName = Path.GetFileName(filePath);
                    long fileSize;
                    long downloaded = 0;
                    if (long.TryParse(parts[1].Trim(), out fileSize))
                    {
                        var fileInfo = new FileInfo(filePath);
                        if (fileInfo.Exists)
                            downloaded = fileInfo.Length;
                        else
                            RemoveFileFromList(fileName);

CorpServer/Views/System/ConnectionsPerDay.cshtml
@using System.Globalization;
@using Tools;
@using Models.ViewModel;

@model FailedLoginsVm
@{
    ViewBag.Title = "Connections Stats";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 style="display:inline-block;">Connections Stats</h3>
<h6 style="display:inline-block;">
    &ensp;
    loading time : @(TempData["LoadingTime"]?.ToString())
</h6>

<div class="text-success">@(TempData["SuccessMessage"]?.ToString())</div>
<div class="text-warning">@(TempData["ErrorMessage"]?.ToString())</div>
@if (Model != null)
{
    PersianCalendar pc = new PersianCalendar();
    var x = "";
    var y = "";

    int len = Model.stats.Count();

    int visit = Model.stats[len-1];
    int min = visit, max = visit;
    var interval = len;
    int temp = 0;
    int start_point = len;
    while (temp != 3 && start_point > 0)
    {
        start_point--;
        if (Model.dates[start_point].ToString("hh tt") == "12 AM")
        {
            temp++;
        }
    }
    for (int i = start_point; i < len; i++)
    {
        var time = int.Parse(Model.dates[i].ToString("HH"));
        if (time == 0)
        {
            x += "(" + pc.GetDayOfMonth(Model.dates[i]) + " " + PersianDate.MonthIndexToName(pc.GetMonth(Model.dates[i]), finglish: true) + ")";
        }
        else
        {
            x += time;
        }

        visit = Model.stats[i];
        max = visit > max ? visit : max;

        y += visit.ToString();
        if (i != len - 1)
        {
            x += ",";
            y += ",";
        }
    }
    max = (int)(max * 1.1);
    min = (int)(min * 1.0 - 0.1 * max);


    <div id="SiteVisitX" class="hidden">
        @x
    </div>
    <div id="SiteVisitY" class="hidden">
        @y
    </div>
    <div id="minVisits" class="hidden">
        @min
    </div>
    <div id="maxVisits" class="hidden">
        @max
    </div>
    <br />

    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-chart-area"></i>
        </div>
        
        <canvas id="myAreaChart"></canvas>
        
        <div class="card-footer small text-muted"></div>
    </div>
}

@section EndSectionForScripts{
    <script>
        // Set new default font family and font color to mimic Bootstrap's default styling
        Chart.defaults.global.defaultFontFamily = '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
        Chart.defaults.global.defaultFontColor = '#292b2c';

        var days = document.getElementById("SiteVisitX").innerHTML.split(",");
        var visits = document.getElementById("SiteVisitY").innerHTML.split(",");


        var minVisit = parseInt(document.getElementById("minVisits").innerHTML);
        var maxVisit = parseInt(document.getElementById("maxVisits").innerHTML);


        // Area Chart Example
        var ctx = document.getElementById("myAreaChart");
        var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: days,
                datasets: [{
                    label: "Connections",
                    lineTension: 0.3,
                    backgroundColor: "rgba(2,117,216,0.2)",
                    borderColor: "rgba(2,117,216,1)",
                    pointRadius: 2,
                    pointBackgroundColor: "rgba(2,117,216,1)",
                    pointBorderColor: "rgba(255,255,255,0.8)",
                    pointHoverRadius: 4,
                    pointHoverBackgroundColor: "rgba(2,117,216,1)",
                    pointHitRadius: 50,
                    pointBorderWidth: 1,
                    data: visits,
                    spanGaps: true
                }],
            },
            options: {
                responsive: true,
                bounds: 'ticks',
                scales: {

                    xAxes: [{
                        time: {
                            unit: 'date'
                        },
                        stacked: true,
                        time: {
                            unit: 'string'
                        },
                        gridLines: {
                            display: true
                        },
                        ticks: {
                            maxTicksLimit: 7
                        }
                    }],
                    yAxes: [{
                        ticks: {
                            min: 0,
                            max: maxVisit,
                            maxTicksLimit: 5
                        },
                        gridLines: {
                            color: "rgba(0, 0, 0, .125)",
                        }
                    }],
                },
                legend: {
                    display: false
                }
            }
        });
    </script>
}

CorpServer/Views/System/FileViewer.cshtml
@model FileInfo

@{
    ViewBag.Title = "FileViewer";
    Layout = "~/Views/Shared/_Layout_public.cshtml";
    string fileName = Model.Name;
    string filePath = (Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/') + "/Uploads/" + fileName).ToLower();
    string short_name = Path.GetFileNameWithoutExtension(fileName);
    int size = 20;
    if (short_name.Length > size)
    {
        short_name = short_name.Substring(0, size) + "..";
    }

}

<h3>File Information</h3>
<table class="table table-striped">
    <tr>
        <td>File Name</td>
        <td>Size</td>
        <td>Creation Date</td>
        <td></td>
    </tr>
    <tr>
        <td>
            @short_name@Model.Extension
        </td>
        <td>@Models.Common.InfoTransferUnit.ParseBytes(Model.Length).ToString()</td>
        <td>@Model.CreationTime.ToString("M/d/yy H:mm")</td>

        <td>
            <a href="@filePath">
                <img src="~/Content/download.png" alt="Download" style="max-height: 20px; max-width: 20px;">
            </a>
        </td>
    </tr>
</table>


<div>
    @if (filePath.EndsWith(".jpg") || filePath.EndsWith(".jpeg") || filePath.EndsWith(".png") || filePath.EndsWith(".gif"))
    {
        <img src="@Url.Content(filePath)" alt="Image" style="max-width:100%" />
    }
    else if (filePath.EndsWith(".mp4") || filePath.EndsWith(".avi") || filePath.EndsWith(".mov") || filePath.EndsWith(".mkv"))
    {
        <video src="@Url.Content(filePath)" controls style="max-width:100%">
            Your browser does not support the video tag.
        </video>
    }
    else
    {
        <p>File format not supported.</p>
    }
</div>

CorpServer/Views/System/ListFilesPartial.cshtml
@model List<FileInfo>
@{ var supported_view_formats = new List<string>() { ".jpg", ".jpeg", ".png", ".gif", ".mp4", ".avi", ".mov", ".mkv" };}
<style>
    .copy-link-button {
        color: #fff;
        background-color: #17a2b8;
        border-color: #17a2b8;
        padding: .25rem .5rem;
        font-size: .875rem;
        line-height: 1.5;
        border-radius: .2rem;
    }

        .copy-link-button:hover {
            background-color: #138496;
            border-color: #117a8b;
        }

    .delete-button {
        color: #fff;
        background-color: #dc3545;
        border-color: #dc3545;
        padding: .25rem .5rem;
        font-size: .875rem;
        line-height: 1.5;
        border-radius: .2rem;
    }

        .delete-button:hover {
            background-color: #c82333;
            border-color: #bd2130;
        }

    .progress-bar-small {
        display: none;
        width: 100%;
        padding: 5px 5px;
        background-color: #ddd;
        position: relative;
        margin-top: 20px;
    }

    .progress-bar-small-fill {
        height: 100%;
        background-color: #4CAF50;
        position: absolute;
        top: 0;
        left: 0;
        width: 0;
    }
    .table td {
        max-width: 300px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
    .scrollable-filename {
        overflow: auto;
        white-space: nowrap;
    }
</style>

<script>
    function deleteFileLine(fileName) {
        $.ajax({
            type: "POST",
            url: "@Request.ApplicationPath/System/RemoveFileFromList",
            data: { fileName: fileName },
            success: function (response) {
                // Handle success response
                console.log("File line removed successfully.");
            },
            error: function (xhr, status, error) {
                // Handle error response
                console.log("Error removing file line.");
            }
        });
    }
    $(document).ready(function () {
        // Define a function to call the AJAX request and handle the response
        function getFileSizes() {
            $.ajax({
                type: "GET",
                url: "@Request.ApplicationPath/System/GetUploadedFilesJson",
                success: function (data) {
                    var fileSizes = JSON.parse(data);
                    var message = "";
                    for (var fileName in fileSizes) {
                        var asciiString = fileSizes[fileName].Item3.trim().split('').map(function (char) { return char.charCodeAt(0); }).join('_');

                        if (fileSizes[fileName].Item1 < fileSizes[fileName].Item2) {
                            $('#' + asciiString).parent().show();
                            $('#' + asciiString).css('width', (fileSizes[fileName].Item1 / fileSizes[fileName].Item2) * 100 + '%');
                            $('#size_' + asciiString).text(fileSizes[fileName].Item4);
                        } else {
                            $('#' + asciiString).parent().hide();
                            deleteFileLine(fileSizes[fileName].Item3.trim());
                        }
                    }
                }
            });
        }

        // Call getFileSizes() every 5 seconds
        setInterval(getFileSizes, 5000);
    });
</script>

@if (Model.Count() != 0)
{
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 50%;">File Name</th>
                    <th style="width: 27%;">Actions</th>
                    <th style="width: 8%;">Size</th>
                    <th style="width: 8%;">Created Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var file in Model)
                {
                    string fileFullName = Path.GetFileName(file.FullName);

                    string[] asciiCodes = new string[fileFullName.Length];
                    for (int i = 0; i < fileFullName.Length; i++)
                    {
                        int asciiCode = (int)fileFullName[i];
                        asciiCodes[i] = asciiCode.ToString();
                    }
                    string asciiString = string.Join("_", asciiCodes);


                    var fileName = Path.GetFileNameWithoutExtension(file.FullName);
                    var fileExt = Path.GetExtension(file.FullName);
                    
                    var fullUrl = Request.Url.Scheme + "://" + Request.Url.Host + "/Down/" + file;
                    var size = Models.Common.InfoTransferUnit.ParseBytes(file.Length).ToString();

                    <tr>
                        <td>
                            <a class="scrollable-filename" href="@fullUrl">@fileName@fileExt</a>
                            <div class="progress-bar-small">
                                <div id="@asciiString" class="progress-bar-small-fill"></div>
                            </div>
                        </td>
                        <td>
                            <button type="button" class="btn btn-secondary btn-xs" onclick="copyToClipboard('@fullUrl')">Copy Link</button>
                            @Html.ActionLink("Remove", "Delete", "System", new { fileName = file }, new { @class = "btn btn-danger btn-xs delete-link", data_file = file })
                            @if (supported_view_formats.Contains(file.Extension.ToLower()))
                            {
                                @Html.ActionLink("View", "FileViewer", "System", new { fileName = Tools.Encryption.ObfuscateFileName(file.Name) }, new { @class = "btn btn-primary btn-xs", target = "_blank" })
                            }
                        </td>
                        <td id="size_@asciiString">@size</td>
                        <td>@file.CreationTime.ToString("M/d/yy H:mm")</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js"></script>
<script>
    function copyToClipboard(text) {
        var dummy = document.createElement("textarea");
        document.body.appendChild(dummy);
        dummy.value = text;
        dummy.select();
        document.execCommand("copy");
        document.body.removeChild(dummy);
        //alert("Link copied to clipboard: " + text);
    }
    $(document).ready(function () {
        $('.delete-link').click(function (e) {
            e.preventDefault();
            var file = $(this).data('file');
            if (confirm('Are you sure you want to delete "' + file + '"?')) {
                window.location.href = $(this).attr('href');
            }
        });
    });
</script>

CorpServer/Views/System/Settings.cshtml
@model Models.ServerSetting

@{
    ViewBag.Title = "Server Settings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Server Settings</h3>

<div class="text-success">@(TempData["SuccessMessage"]?.ToString())</div>
<div class="text-warning">@(TempData["ErrorMessage"]?.ToString())</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <br />
    if (Model != null)
    {
        <table class="col-md-5 table">
            <tr>
                <th>@Html.LabelFor(model => model.IpAddress, htmlAttributes: new { @class = "control-label col-md-7" })</th>
                <th>
                    @Html.EditorFor(model => model.IpAddress)
                    @Html.ValidationMessageFor(model => model.IpAddress, "", new { @class = "text-danger" })
                </th>
            </tr>
            <tr>
                <th>@Html.LabelFor(model => model.RdpRuleStatus, htmlAttributes: new { @class = "control-label col-md-7" })</th>
                <th>
                    @Html.EditorFor(model => model.RdpRuleStatus)
                    @Html.ValidationMessageFor(model => model.RdpRuleStatus, "", new { @class = "text-danger" })
                </th>
            </tr>
            <tr>
                <th>
                    @Html.LabelFor(model => model.ClientsCanChangePass, htmlAttributes: new { @class = "control-label col-md-7" })
                </th>
                <th>
                    @Html.EditorFor(model => model.ClientsCanChangePass)
                    @Html.ValidationMessageFor(model => model.ClientsCanChangePass, "", new { @class = "text-danger" })
                </th>
            </tr>
        </table>
        <input type="submit" value="Save" class="btn btn-default" />
    }
}

CorpServer/Views/System/Upload.cshtml
@model List<FileInfo>
@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Upload a File</h2>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Upload", "System", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "uploadFile(); return false;", id = "localUploadForm" }))
        {
            <h3>Local File</h3>
            <div class="form-group">
                <label for="fileInput">Select file to upload:</label>
                <input type="file" id="fileInput" name="file" required aria-describedby="fileHelpText">
                <small id="fileHelpText" class="form-text text-muted">Select a file from your local device.</small>
            </div>
            <button type="submit" class="btn btn-primary" id="localUploadBtn">Upload</button>
        }
    </div>
    <div class="col-md-6">
        @using (Html.BeginForm("UploadFromLink", "System", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "uploadFile(); return false;", id = "urlUploadForm" }))
        {
            <h3>From Url</h3>
            <div class="form-group">
                <label for="urlInput">Enter URL:</label>
                <input type="url" id="urlInput" name="url" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-primary" id="urlUploadBtn">Upload</button>
            <br /><br />
            <div class="alert alert-info" style="display: none;">File upload Started.</div>
        }
    </div>
</div>
<br />
<div class="progress mt-3" style="display: none; margin-top:1em;">
    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
        <span class="sr-only">0% Complete</span>
    </div>
</div>
<br />
<div class="alert alert-success" style="display: none;">File uploaded successfully.</div>
<div class="alert alert-danger" style="display: none;">An error occurred while uploading the file.</div>

<div id="files-partial-container">
    @Html.Partial("ListFilesPartial", Model)
</div>

@section scripts{
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#localUploadBtn').click(function () {
                var file = $('#file').val();
                if (file == "") {
                    alert("Please select a file to upload.");
                    return false;
                }
          });

          $('#urlUploadBtn').click(function () {
            var url = $('#urlInput').val();
            if (url == "") {
              alert("Please enter a URL to upload from.");
              return false;
            }
          });
        });

        $(function () {
            $('#localUploadForm').ajaxForm({
                beforeSend: function () {
                    // Show the progress bar
                    $('.progress').show();
                },
                uploadProgress: function (event, position, total, percentComplete) {
                    // Update the progress bar with the new percent value
                    $('.progress-bar').width(percentComplete + '%');
                    $('.progress-bar').attr('aria-valuenow', '0').text(percentComplete + '% Complete');
                    $('.sr-only').text(percentComplete + '% Complete');
                },
                success: function () {
                    // Hide the progress bar and show a success message
                    $('#files-partial-container').load('@Url.Action("FilesPartial")');
                    $('.progress-bar').css('width', '0%').attr('aria-valuenow', '0').text('0% Complete');
                    $('.progress').hide();
                    $('.alert-success').show();
                },
                error: function (xhr, status, error) {
                    alert(error);
                    // Hide the progress bar and show an error message
                    $('.progress-bar').css('width', '0%').attr('aria-valuenow', '0').text('0% Complete');
                    $('.progress').hide();
                    $('.alert-danger').show();
                }
            });

            $('#urlUploadForm').ajaxForm({
                beforeSend: function () {
                    $('.alert-info').show();
                },
                uploadProgress: function (event, position, total, percentComplete) {
                    $('#files-partial-container').load('@Url.Action("FilesPartial")');
                },
                success: function () {
                    // Hide the progress bar and show a success message
                    $('#files-partial-container').load('@Url.Action("FilesPartial")');
                    $('.alert-success').show();
                    $('.alert-info').hide();
                },
                error: function (xhr, status, error) {
                    //alert(error);
                    //$('.alert-danger').show();
                }
            });
        });
    </script>
}